=== blpk11/BDA-460321916/Ejercicios_02_09/pedidos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Tienda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Articulos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Articulo" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Id" type="xs:string"/>
                                        <xs:element name="Nombre" type="xs:string"/>
                                        <xs:element name="Precio" type="xs:decimal"/>
                                        <xs:element name="Existencias" type="xs:int"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== blpk11/BDA-460321916/XML/Ejercicios_02_09/Ejercicio_02_09.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Héctor Santiago Loyde Figueroa -->
<Tienda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="pedidos.xsd">
<Articulos>

    <Articulo>
        <Id>L001</Id>
        <Nombre>Leche</Nombre>
        <Precio>30.50</Precio>
        <Existencias>30</Existencias>
    </Articulo>

    <Articulo>
        <Id>H101</Id>
        <Nombre>Huevo</Nombre>
        <Precio>27.80</Precio>
        <Existencias>15</Existencias>
    </Articulo>

    <Articulo>
        <Id>Q201</Id>
        <Nombre>Queso</Nombre>
        <Precio>40.70</Precio>
        <Existencias>50</Existencias>
    </Articulo>

    <Articulo>
        <Id>M301</Id>
        <Nombre>Mantequilla</Nombre>
        <Precio>15.99</Precio>
        <Existencias>35</Existencias>
    </Articulo>

    </Articulos>
</Tienda>
