=== blpk11/BDA-460321916/XML/mascotas/mascotas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="veterinaria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="clientes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cliente" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ID_Cliente" type="xs:string"/>
                                        <xs:element name="Nombre_Cliente" type="xs:string"/>
                                        <xs:element name="Teléfono" type="xs:string"/>
                                        <xs:element name="Nombre_Mascota" type="xs:string"/>
                                        <xs:element name="Especie" type="xs:string"/>
                                        <xs:element name="Servicio" type="xs:string"/>
                                        <xs:element name="Fecha" type="xs:date"/>
                                        <xs:element name="Costo" type="xs:decimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== blpk11/BDA-460321916/mascotas/tienda_mascotas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Héctor Santiago Loyde Figueroa -->
<veterinaria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="mascotas.xsd">
<clientes>
    <cliente>
        <ID_Cliente>C-101</ID_Cliente>
        <Nombre_Cliente>Carlos Ruiz</Nombre_Cliente>
        <Teléfono>555-1234</Teléfono>
        <Nombre_Mascota>Toby</Nombre_Mascota>
        <Especie>Perro</Especie>
        <Servicio>Baño y corte</Servicio>
        <Fecha>2026-03-10</Fecha>
        <Costo>350</Costo>
    </cliente>
    <cliente>
        <ID_Cliente>C-101</ID_Cliente>
        <Nombre_Cliente>Carlos Ruiz</Nombre_Cliente>
        <Teléfono>555-1234</Teléfono>
        <Nombre_Mascota>Toby</Nombre_Mascota>
        <Especie>Perro</Especie>
        <Servicio>Vacuna y antirrabia</Servicio>
        <Fecha>2026-03-10</Fecha>
        <Costo>250</Costo>
    </cliente>
    <cliente>
        <ID_Cliente>C-102</ID_Cliente>
        <Nombre_Cliente>Laura Gomez</Nombre_Cliente>
        <Teléfono>555-5678</Teléfono>
        <Nombre_Mascota>Michi</Nombre_Mascota>
        <Especie>Gato</Especie>
        <Servicio>Desparacitación</Servicio>
        <Fecha>2026-03-11</Fecha>
        <Costo>180</Costo>
    </cliente>
    <cliente>
        <ID_Cliente>C-102</ID_Cliente>
        <Nombre_Cliente>Laura Gomez</Nombre_Cliente>
        <Teléfono>555-5678</Teléfono>
        <Nombre_Mascota>Michi</Nombre_Mascota>
        <Especie>Gato</Especie>
        <Servicio>Limpieza Dental</Servicio>
        <Fecha>2026-03-11</Fecha>
        <Costo>400</Costo>
    </cliente>
        <cliente>
        <ID_Cliente>C-103</ID_Cliente>
        <Nombre_Cliente>Roberto Díaz</Nombre_Cliente>
        <Teléfono>555-9012</Teléfono>
        <Nombre_Mascota>Max</Nombre_Mascota>
        <Especie>Perro</Especie>
        <Servicio>Revisión General</Servicio>
        <Fecha>2026-03-12</Fecha>
        <Costo>300</Costo>
    </cliente>
    <cliente>
        <ID_Cliente>C-103</ID_Cliente>
        <Nombre_Cliente>Roberto Díaz</Nombre_Cliente>
        <Teléfono>555-9012</Teléfono>
        <Nombre_Mascota>Max</Nombre_Mascota>
        <Especie>Perro</Especie>
        <Servicio>Corte de uñas</Servicio>
        <Fecha>2026-03-12</Fecha>
        <Costo>100</Costo>
    </cliente>
</clientes>
</veterinaria>
